version: '3'
services:

  synse-server:
    container_name: synse-server
    image: vaporio/synse-server
    ports:
    - '5000:5000'
    links:
    - emulator
    environment:
      SYNSE_LOGGING: debug
      SYNSE_PLUGIN_TCP: emulator:5001
      SYNSE_METRICS_ENABLED: 'true'

  emulator:
    container_name: emulator
    image: vaporio/emulator-plugin
    ports:
    - '5001:5001'
    - '2112:2112'
    command: ['--debug']
    environment:
      PLUGIN_METRICS_ENABLED: "true"

  loadgen:
    container_name: loadgen
    image: vaporio/synse-loadgen
    environment:
      SLG_SYNSE_HOST: synse-server
    links:
    - synse-server

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
    - ./prometheus/config.yaml:/etc/prometheus/prometheus.yml
    ports:
    - '9090:9090'
    links:
    - synse-server
    - emulator

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
    - '3000:3000'
    volumes:
    - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
    - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    - ./grafana/dashboards:/var/lib/grafana/dashboards
    links:
    - prometheus