version: 2
jobs:
  build:
    docker:
      - image: vaporio/build-base:68a4171
    working_directory: ~/code

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true
          exclusive: false
          version: 17.06.0-ce

      - run:
          name: check 1
          command: |
            ls .tox/unit || true

      - restore_cache:
          keys:
            - v1.2-tox-test-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
            - v1.2-tox-test-cache- # used if checksum fails

      - run:
          name: check 2
          command: |
            ls .tox/unit || true

      - run:
          name: Unit Tests
          command: |
            bin/circleci.sh unit

      - run:
          name: check 3
          command: |
            ls .tox/unit || true

      - save_cache:
          when: always
          key: v1.2-tox-test-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - .tox/unit

      - run:
          name: check 4
          command: |
            ls .tox/lint || true

      - restore_cache:
          keys:
            - v2.3-tox-lint-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
            - v2.3-tox-lint-cache- # used if checksum fails

      - run:
          name: check 5
          command: |
            ls .tox/lint || true

      - run:
          name: Lint
          command: |
            bin/circleci.sh lint

      - run:
          name: check 6
          command: |
            ls .tox/lint || true

      - save_cache:
          when: always
          key: v2.3-tox-lint-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - .tox/lint

      - store_artifacts:
          path: /tmp/
          destination: test-output

      - store_test_results:
          path: /tmp/test-results
