version: 2
jobs:
  build:
    docker:
      - image: vaporio/build-base
    working_directory: ~/code

    steps:
      - checkout

      - setup_remote_docker:

      - run:
          name: Build Images
          command: |
            make build
            docker login -u ${DOCKER_USER} -p ${DOCKER_PS}
            docker push vaporio/synse-server

      - restore_cache:
          keys:
            - v1.2-tox-test-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
            - v1.2-tox-test-cache- # used if checksum fails

      - run:
          name: Unit Tests
          command: |
            bin/circleci.sh unit

      - save_cache:
          when: always
          key: v1.2-tox-test-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - .tox/unit

      - restore_cache:
          keys:
            - v2.3-tox-lint-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
            - v2.3-tox-lint-cache- # used if checksum fails

      - run:
          name: Lint
          command: |
            bin/circleci.sh lint

      - save_cache:
          when: always
          key: v2.3-tox-lint-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - .tox/lint

      - store_artifacts:
          path: /tmp/
          destination: test-output

      - store_test_results:
          path: /tmp/test-results
