version: 1.0
type: led
model: emul8-led

locations:
  r1vec:
    rack: rack-1
    board: vec

devices:
  - id: "1"
    location: r1vec
    info: Synse LED
  - id: "2"
    location: r1vec
    info: Synse backup LED
