version: 1.0
prototypes:
  - type: led
    model: emul8-led
    manufacturer: Vapor IO
    protocol: emulator
    output:
      - type: state
        data_type: string
      - type: color
        data_type: string