global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "synse-server"
    static_configs:
      - targets: ["synse-server:5000"]
  - job_name: "emulator"
    static_configs:
      - targets: ["emulator:2112"]
