version: 1.0
type: emulated-fan
model: emul8-fan
manufacturer: vaporio
protocol: emulator
output:
  - type: fan_speed
    unit:
      name: revolutions per minute
      symbol: RPM
    precision: 1
    range:
      min: 0
      max: 100