# RS-485 Development Composefile
#   a composefile that defines a development environment for RS-485. it builds
#   a synse server container and RS-485 emulator and links them.
version: "3"
services:
  synse-server-dev:
    container_name: synse-server-dev
    image: vaporio/synse-server-dev
    build:
      context: ..
      dockerfile: dockerfile/release.dockerfile
    links:
      - synse-test-container

  synse-test-container:
    container_name: synse-server-test
    image: vaporio/synse-server-rs485
    build:
      context: ..
      dockerfile: dockerfile/release.dockerfile
    command: emulate-rs485
    expose:
      - 5000
    environment:
      - VAPOR_DEBUG=true
    volumes:
      - ../synse/tests/data/rs485_emulator/rs485_emulator_config-002.json:/synse/rs485_config.json
