# I2C Development Composefile
#   a composefile that defines a development environment for I2C. it builds
#   a synse server container and I2C emulator and links them.
version: "3"
services:
  synse-server-dev:
    container_name: synse-server-dev
    image: vaporio/synse-server-dev
    build:
      context: ..
      dockerfile: dockerfile/release.dockerfile
    links:
      - synse-test-container

  synse-test-container:
    container_name: synse-server-test
    image: vaporio/synse-server-i2c
    build:
      context: ..
      dockerfile: dockerfile/release.dockerfile
    command: emulate-i2c
    expose:
      - 5000
    environment:
      - VAPOR_DEBUG=true
