# SNMP Development Composefile
#   a composefile that defines a development environment for SNMP. it builds
#   a synse server container and SNMP emulator and links them.
version: "3"
services:
  synse-server-dev:
    container_name: synse-server-dev
    image: vaporio/synse-server-dev
    build:
      context: ..
      dockerfile: dockerfile/release.dockerfile
    links:
      - snmp-emulator-test

  snmp-emulator-test:
    container_name: snmp-emulator
    image: vaporio/snmp-emulator
    build:
      context: ../synse/emulator/snmp
      dockerfile: Dockerfile-synse-testdevice1-board1.x64
    command: ./start_snmp_emulator.sh ./data 11012 snmp-emulator.log
    ports:
      - 11012:11012/udp
    environment:
      - VAPOR_DEBUG=true