# PLC Development Composefile
#   a composefile that defines a development environment for PLC. it builds
#   a synse server container and PLC emulator and links them.
version: "3"
services:
  synse-server-dev:
    container_name: synse-server-dev
    image: vaporio/synse-server-dev
    build:
      context: ..
      dockerfile: dockerfile/release.dockerfile
    links:
      - synse-test-container

  synse-test-container:
    container_name: synse-server-test
    image: vaporio/synse-server-plc
    build:
      context: ..
      dockerfile: dockerfile/release.dockerfile
    command: emulate-plc-with-cfg ./synse/emulator/plc/data/example.json
    expose:
      - 5000
    environment:
      - VAPOR_DEBUG=true
