version: "3"
services:
  synse-dev:
    container_name: synse-dev
    image: vaporio/synse-server:${GIT_VER}
    build:
      context: ..
      dockerfile: dockerfile/test.dockerfile
    volumes:
      - ..:/code
    command: bin/sleep.sh
    ports:
      - 5000:5000