version: "2"
services:
  graphql-release:
    container_name: synse_graphql
    image: vaporio/synse_graphql
    build:
      context: ..
      dockerfile: dockerfile/graphql-release.dockerfile
    volumes:
      - ../VERSION:/VERSION
    ports:
      - "5000:5000"
