version: "3"
services:
  synse-test:
    container_name: synse-test
    image: vaporio/synse-server:${GIT_VER}
    build:
      context: ..
      dockerfile: dockerfile/test.dockerfile
    volumes:
      - ..:/code
    command: bin/run_tests.sh integration

  synse:
    container_name: synse
    image: vaporio/synse-server:${GIT_VER}
    build:
      context: ..
      dockerfile: dockerfile/release.dockerfile
    command: ["emulate-rs485"]
    environment:
      - VAPOR_DEBUG=true
    ports:
      - 5000:5000
