#
# compose/test.yml
#
# The base compose file for running tests. Tests that will run
# via compose files should use this as the base.
#
# Example:
#   docker-compose -f test.yml -f unit.yml up
#
version: "3"
services:
  synse-test:
    container_name: synse-test
    image: vaporio/synse-server-test:local
    build:
      context: ..
      dockerfile: dockerfile/test.dockerfile
    volumes:
      - ..:/code
